// Code generated by counterfeiter. DO NOT EDIT.
package arithmeticfakes

import (
	"sync"

	"github.com/kieron-dev/lsbasi/arithmetic"
	"github.com/kieron-dev/lsbasi/lexer"
)

type FakeTokeniser struct {
	NextTokenStub        func() (lexer.Token, error)
	nextTokenMutex       sync.RWMutex
	nextTokenArgsForCall []struct {
	}
	nextTokenReturns struct {
		result1 lexer.Token
		result2 error
	}
	nextTokenReturnsOnCall map[int]struct {
		result1 lexer.Token
		result2 error
	}
	invocations      map[string][][]interface{}
	invocationsMutex sync.RWMutex
}

func (fake *FakeTokeniser) NextToken() (lexer.Token, error) {
	fake.nextTokenMutex.Lock()
	ret, specificReturn := fake.nextTokenReturnsOnCall[len(fake.nextTokenArgsForCall)]
	fake.nextTokenArgsForCall = append(fake.nextTokenArgsForCall, struct {
	}{})
	stub := fake.NextTokenStub
	fakeReturns := fake.nextTokenReturns
	fake.recordInvocation("NextToken", []interface{}{})
	fake.nextTokenMutex.Unlock()
	if stub != nil {
		return stub()
	}
	if specificReturn {
		return ret.result1, ret.result2
	}
	return fakeReturns.result1, fakeReturns.result2
}

func (fake *FakeTokeniser) NextTokenCallCount() int {
	fake.nextTokenMutex.RLock()
	defer fake.nextTokenMutex.RUnlock()
	return len(fake.nextTokenArgsForCall)
}

func (fake *FakeTokeniser) NextTokenCalls(stub func() (lexer.Token, error)) {
	fake.nextTokenMutex.Lock()
	defer fake.nextTokenMutex.Unlock()
	fake.NextTokenStub = stub
}

func (fake *FakeTokeniser) NextTokenReturns(result1 lexer.Token, result2 error) {
	fake.nextTokenMutex.Lock()
	defer fake.nextTokenMutex.Unlock()
	fake.NextTokenStub = nil
	fake.nextTokenReturns = struct {
		result1 lexer.Token
		result2 error
	}{result1, result2}
}

func (fake *FakeTokeniser) NextTokenReturnsOnCall(i int, result1 lexer.Token, result2 error) {
	fake.nextTokenMutex.Lock()
	defer fake.nextTokenMutex.Unlock()
	fake.NextTokenStub = nil
	if fake.nextTokenReturnsOnCall == nil {
		fake.nextTokenReturnsOnCall = make(map[int]struct {
			result1 lexer.Token
			result2 error
		})
	}
	fake.nextTokenReturnsOnCall[i] = struct {
		result1 lexer.Token
		result2 error
	}{result1, result2}
}

func (fake *FakeTokeniser) Invocations() map[string][][]interface{} {
	fake.invocationsMutex.RLock()
	defer fake.invocationsMutex.RUnlock()
	fake.nextTokenMutex.RLock()
	defer fake.nextTokenMutex.RUnlock()
	copiedInvocations := map[string][][]interface{}{}
	for key, value := range fake.invocations {
		copiedInvocations[key] = value
	}
	return copiedInvocations
}

func (fake *FakeTokeniser) recordInvocation(key string, args []interface{}) {
	fake.invocationsMutex.Lock()
	defer fake.invocationsMutex.Unlock()
	if fake.invocations == nil {
		fake.invocations = map[string][][]interface{}{}
	}
	if fake.invocations[key] == nil {
		fake.invocations[key] = [][]interface{}{}
	}
	fake.invocations[key] = append(fake.invocations[key], args)
}

var _ arithmetic.Tokeniser = new(FakeTokeniser)
